version: "3.7"

services:

    # image project
    app:
        build:
            args:
                user: fabio
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: maieutica
        container_name: maieutica_app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - vige

    # nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        container_name: maieutica_nginx
        ports:
            - 80:80
        volumes:
            - ./:/var/www
            - ./docker/nginx:/etc/nginx/conf.d
        networks:
            - vige

    # mysql
    mysql:
        image: mysql:5.7.23
        container_name: maieutica_db
        restart: unless-stopped
        tty: true
        environment:
            MYSQL_ROOT_PASSWORD: pass
            MYSQL_DATABASE: maieutica
            MYSQL_USER: root
            MYSQL_PASSWORD: pass
            TZ: America/Sao_Paulo
        ports:
            - "3306:3306"
        volumes:
            - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
        networks:
            - vige

    # queue
    queue:
        build:
            args:
                user: fabio
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        restart: unless-stopped
        container_name: maieutica_queue
        command: "php artisan queue:work"
        volumes:
            - ./:/var/www
        networks:
            - vige

networks:
    vige:
        driver: bridge
