<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class GeneratedDocument extends Model
{
    use HasFactory, SoftDeletes;

    protected $fillable = [
        'document_template_id',
        'kid_id',
        'checklist_id',
        'user_id',
        'file_path',
        'data_used',
        'generated_at',
    ];

    protected $casts = [
        'data_used' => 'array',
        'generated_at' => 'datetime',
    ];

    /**
     * Relationship: Document belongs to a template
     */
    public function documentTemplate()
    {
        return $this->belongsTo(DocumentTemplate::class);
    }

    /**
     * Relationship: Document belongs to a kid
     */
    public function kid()
    {
        return $this->belongsTo(Kid::class);
    }

    /**
     * Relationship: Document belongs to a checklist (optional)
     */
    public function checklist()
    {
        return $this->belongsTo(Checklist::class);
    }

    /**
     * Relationship: Document was generated by a user
     */
    public function user()
    {
        return $this->belongsTo(User::class);
    }

    /**
     * Scope: Filter by kid
     */
    public function scopeByKid($query, $kidId)
    {
        return $query->where('kid_id', $kidId);
    }

    /**
     * Scope: Filter by template
     */
    public function scopeByTemplate($query, $templateId)
    {
        return $query->where('document_template_id', $templateId);
    }

    /**
     * Scope: Filter by user
     */
    public function scopeByUser($query, $userId)
    {
        return $query->where('user_id', $userId);
    }

    /**
     * Get the file name from the file path
     */
    public function getFileNameAttribute()
    {
        return basename($this->file_path);
    }

    /**
     * Get the download URL for the document
     */
    public function getDownloadUrlAttribute()
    {
        return route('documents.show', $this->id);
    }
}
